### PR TITLE
Update raml-rb gem

### PR DESCRIPTION
**Pull request by danascheider**
This updates the required version of the raml-rb gem to 0.0.6, which has not yet been released.

### CODE REVIEW

**Comment by dolan** [comment]
Have you considered using a complete RAML parser?  Working around raml-rb's limitations seems like a fool's errand.  https://github.com/coub/raml_ruby already does all of the attributes, and you can ignore/skip the ones you don't want to use. This would make it so that nobody has to trim out the unsupported attributes in their actual RAML files (which need to be complete if they're generating documentation, with something like raml2html) just to work with rambo.

**Comment by danascheider** [comment]
@dolan Yeah, for some reason when I initially looked for a RAML parser, raml-rb was the one I found. Now that I know there are others I'm definitely looking at making the switch. The good news is we now have a second full-time dev working on Rambo, so these things will hopefully be resolved more quickly in the future. Believe me, we're paying two full-time devs for this (including me) - we need it to work too!

**Comment by dolan** [comment]
Glad to hear it. I hope you don't think I'm trying to heckle you. I thought that there just might have been a reason that I didn't understand.

**Comment by danascheider** [comment]
Not at all, I appreciate the suggestion and had been thinking about making the change. Initially, I wasn't aware there were better options, so now I just have to figure out how many changes I'd need to make to incorporate a different gem, since I doubt it's a drop-in replacement.

**Comment by danascheider** [comment]
Besides which, I'm an open source maintainer - I'm always glad to see people interested in my projects, especially if they seem to know what they're talking about!

**Comment by danascheider** [comment]
@dolan So it looks like the raml_ruby gem is not actually published to Rubygems, which makes it very difficult to include in the project without some ugly hacks. I'm going to keep looking to see if there's another more complete parser.

**Comment by dolan** [comment]
https://rubygems.org/gems/raml_ruby

**Comment by danascheider** [comment]
Huh, I guess they just didn't update the README? In any case, thanks!

**Comment by danascheider** [comment]
@dolan So I did a spike today to replace `raml-rb` with `raml_ruby`, and it turns out that the latter does not support the RAML 1.0 specification, which all of our projects use. Maybe @zeisler would be able to contribute RAML 1.0 support to `raml_ruby`, but for the time being I'm going to switch back to `raml-rb`. Frustrating that there isn't a better solution.

**Comment by danascheider** [comment]
@jpb - any chance you could publish v. 0.6 to Rubygems?

**Comment by jpb** [comment]
@danascheider done 👍

**Comment by danascheider** [comment]
Yay! Thanks!

**Pull request merged**
